name: CI Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
      GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install required libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev libpng-dev libtiff-dev libwebp-dev
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
      - name: Prepare DB
        run: |
          sudo apt-get install -y sqlite3 libsqlite3-dev
          bundle exec rails db:environment:set RAILS_ENV=test
          bundle exec rails db:create
          bundle exec rails db:schema:load
      - name: Run RSpec tests
        run: bundle exec rspec
